# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
target 'TaskMan' do
  pod 'Stripe', '~> 11.2.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native' # This path is likely to be `../node_modules/react-native` in your own project.
  rn_maps_path = '../node_modules/react-native-maps' # This path is likely to be `../node_modules/react-native-maps` in your own project.
  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  
     # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  
      pod 'RSKImageCropper'
      pod 'QBImagePickerController'
      pod 'GooglePlaces'
      pod 'GooglePlacePicker'
      pod 'Firebase/Core'
      pod 'Firebase/Firestore'
      pod 'Firebase/Storage'
      pod 'Firebase/Auth'
      pod 'Fabric'
      pod 'Crashlytics'
      pod 'Firebase/Messaging'
      pod 'Firebase/Functions'
      pod 'Firebase/Database'
    
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  target 'TaskManTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "react-native-google-maps"
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
      if target.name == "React"
        target.remove_from_project
      end  
  end
end