const lang = {
  en: {
    Login: "Login",
    LoginUser: "Login as User",
    LoginTasker: "Login as CareTaker",
    signup: "Sign Up",
    changelanguage: "Change Language",
    signin: "Sign In",
    emailaddress: "Email Address",
    password: "Password",
    or: "OR",
    facebook: "Facebook",
    google: "Google+",
    name: "Name",
    phoneno: "Phone Number",
    usechar: "Use atleast 8 characters",
    language: "Language",
    myservices: "My Services",
    typeOfServices: "Types of services",
    SelectCategory: "Select Category",
    SubCategory: "Sub Category",
    BecomeTasker: "Become a tasker to see your services",
    SelectSubCategories: "Select Sub categories",
    AverageHourlyCost: "Average Hourly Cost",
    Enterfee: "Enter Fee",
    Address: "Address",
    Update: "Update",
    Save: "Save",
    Search: "Search",
    payment: "Payment",
    changepassword: "Change Password",
    signout: "Sign Out",
    taskman: "Welcome to HCS",
    organized: "Get your task more organised",
    more: "and get more done!",
    getorganized: "Get Organized",
    group: "Get Efficient CareTakers",
    submit: "Submit",
    oldpassword: "Old Password",
    newpassword: "New Password",
    repassword: "Retype New Password",
    show: "show",
    Explore: "Explore",
    favourite: "Favourite",
    NoFavourite: "Oops! No Favourite CareTakers",
    fetchTaskers: "Fetching CareTakers",
    Home: "Home",
    Appointments: "Appointments",
    Earnings: "Earnings",
    TotalEarnings: "Total Earnings",
    TODAY: "TODAY",
    YESTERDAY: "YESTERDAY",
    Week: "WEEK",
    Month: "MONTH",
    Year: "YEAR",
    Received: "Received",
    ReceivedVia: "Received Via",
    task: "Task",
    History: "History",
    bookingHistory: "Booking History",
    Upcoming: "Upcoming",
    Past: "Past",
    NoUpcomingTasks: "No Upcoming Tasks",
    NoTaskHistory: "No Task History",
    ChooseLanguage: "Choose Language",
    EditMyServices: "Edit My Services",
    BecomeaTasker: "Become a Tasker",
    booking: "Booking",
    account: "Account",
    tasker: "CareTaker",
    User: "Switch to User",
    nurse: "Nurse",
    babysitter: "Babysitter",
    Health: "Health",
    physiotherapist: "Physiotherapist",
    Business: "Business",
    Tutors: "Tutors",
    AirConditioning: "Air Conditioning",
    TV: "TV",
    Mobile: "Mobile",
    Geyser: "Geyser",
    WashingMachine: "Washing Machine",
    PestControl: "PestControl",
    Sofa: "Sofa",
    Kitchen: "Kitchen",
    Bathroom: "Bathroom",
    GymTrainer: "GymTrainer",
    Dietician: "Dietician",
    Yoga: "Yoga",
    Psychiatrist: "Psychiatrist",
    Photographer: "Photographer",
    DJ: "DJ",
    Caterer: "Caterer",
    MakeupArtist: "MakeupArtist",
    Lawyer: "Lawyer",
    VisaAgency: "Visa Agency",
    Developers: "Developers",
    CA: "CA",
    Designers: "Designers",
    Primary: "Primary",
    HighSchool: "HighSchool",
    Engineering: "Engineering",
    Medical: "Medical",
    Accountancy: "Accountancy",
    book: "Book",
    booknow: "BOOK NOW",
    confirmbook: "CONFIRM BOOKING",
    Cancel: "Cancel",
    StartTask: "Start Task",
    Start: "Start",
    Done: "Done",
    CompleteTask: "Complete Task",
    CancelBooking: "Cancel Booking",
    taskInProgress: "Task in progress",
    editservice: "Edit My Service",
    bookingconfirmed: "Booking Confirmed",
    bookingCancelled: "Booking has been Cancelled",
    taskerreach: "CareTaker will reach in a few minutes",
    taskprogress:
      "Your requested task is in progress, wait until the task is completed",
    payment: "Payment",
    date: "Date",
    time: "Time",
    services: "Services",
    total: "Total",
    CollectCash: "Collect Cash",
    price: "price",
    userPaying: "Wait user is paying",
    paymentmethod: "Payment Method",
    pay: "Pay",
    howtopay: "Select how you would like to pay",
    card: "Credit/Debit Card",
    cash: "Cash",
    choosecard: "Choose Card",
    addCard: "Add Card",
    selectCard: "Select Card",
    noCards: "You don't have any saved credit cards,\npress + to add new one",
    invalidInput: "Invalid Input",
    rating: "Rating",
    review: "Review",
    submit: "Submit",
    feedback: "Enter your feedback",
    experience: "How did you find the experience?",
    paymentsuccess: "Payment Success",
    paymentFailed: "Payment Failed. please pay in Cash",
    accept: "Accept",
    seconds: "SEC",
    reject: "Reject",
    AFPatientName:"Patient Name",
    AFGender:"Gender",
    AFAge:"Age",
    AFMedicalConditions:"Medical conditions",
    AFAddress:"Address",
    AFSponsorName:"Sponsor Name",
    AFPhoneNumber:"Phone number",
    createAppointment:"Create Appointment",
    editAppointment:"Edit Appointment",
    myAppointments:"My Appointments",
    medicalCondition: "Please enter medical conditions",
  }
};

export default lang;
