const lang = {
  en: {
    Login: "Log In",
    signup: "Sign Up",
    changelanguage: "Change Language",
    signin: "Sign In",
    emailaddress: "Email Address",
    password: "Password",
    or: "OR",
    facebook: "Facebook",
    google: "Google+",
    name: "Name",
    phoneno: "Phone Number",
    usechar: "Use atleast 8 characters",
    language: "Language",
    myservices: "My Services",
    typeOfServices: "Types of services",
    SelectCategory: "Select Category",
    SubCategory: "Sub Category",
    BecomeTasker: "Become a tasker to see your services",
    SelectSubCategories: "Select Sub categories",
    AverageHourlyCost: "Average Hourly Cost",
    Enterfee: "Enter Fee",
    Address: "Address",
    Update: "Update",
    Search: "Search",
    payment: "Payment",
    changepassword: "Change Password",
    signout: "Sign Out",
    taskman: "Welcome to TaskMan",
    organized: "Get your task more organised",
    more: "and get more done!",
    getorganized: "Get Organized",
    group: "Get Efficient Taskers",
    submit: "Submit",
    oldpassword: "Old Password",
    newpassword: "New Password",
    repassword: "Retype New Password",
    show: "show",
    Explore: "Explore",
    favourite: "Favourite",
    NoFavourite: "Oops! No Favourite Taskers",
    fetchTaskers: "Fetching Taskers",
    Home: "Home",
    Earnings: "Earnings",
    TotalEarnings: "Total Earnings",
    TODAY: "TODAY",
    YESTERDAY: "YESTERDAY",
    Week: "WEEK",
    Month: "MONTH",
    Year: "YEAR",
    Received: "Received",
    ReceivedVia: "Received Via",
    task: "Task",
    History: "History",
    bookingHistory: "Booking History",
    Upcoming: "Upcoming",
    Past: "Past",
    NoUpcomingTasks: "No Upcoming Tasks",
    NoTaskHistory: "No Task History",
    ChooseLanguage: "Choose Language",
    EditMyServices: "Edit My Services",
    BecomeaTasker: "Become a Tasker",
    booking: "Booking",
    account: "Account",
    tasker: "Tasker",
    User: "Switch to User",
    Repair: "Repair",
    Cleaning: "Cleaning",
    Health: "Health",
    Wedding: "Wedding",
    Business: "Business",
    Tutors: "Tutors",
    AirConditioning: "Air Conditioning",
    TV: "TV",
    Mobile: "Mobile",
    Geyser: "Geyser",
    WashingMachine: "Washing Machine",
    PestControl: "PestControl",
    Sofa: "Sofa",
    Kitchen: "Kitchen",
    Bathroom: "Bathroom",
    GymTrainer: "GymTrainer",
    Dietician: "Dietician",
    Yoga: "Yoga",
    Psychiatrist: "Psychiatrist",
    Photographer: "Photographer",
    DJ: "DJ",
    Caterer: "Caterer",
    MakeupArtist: "MakeupArtist",
    Lawyer: "Lawyer",
    VisaAgency: "Visa Agency",
    Developers: "Developers",
    CA: "CA",
    Designers: "Designers",
    Primary: "Primary",
    HighSchool: "HighSchool",
    Engineering: "Engineering",
    Medical: "Medical",
    Accountancy: "Accountancy",
    book: "Book",
    booknow: "BOOK NOW",
    confirmbook: "CONFIRM BOOKING",
    Cancel: "Cancel",
    StartTask: "Start Task",
    Start: "Start",
    Done: "Done",
    CompleteTask: "Complete Task",
    CancelBooking: "Cancel Booking",
    taskInProgress: "Task in progress",
    editservice: "Edit My Service",
    bookingconfirmed: "Booking Confirmed",
    bookingCancelled: "Booking has been Cancelled",
    taskerreach: "Tasker will reach in a few minutes",
    taskprogress:
      "Your requested task is in progress, wait until the task is completed",
    payment: "Payment",
    date: "Date",
    time: "Time",
    services: "Services",
    total: "Total",
    CollectCash: "Collect Cash",
    price: "price",
    userPaying: "Wait user is paying",
    paymentmethod: "Payment Method",
    pay: "Pay",
    howtopay: "Select how you would like to pay",
    card: "Credit/Debit Card",
    cash: "Cash",
    choosecard: "Choose Card",
    addCard: "Add Card",
    selectCard: "Select Card",
    noCards: "You don't have any saved credit cards,\npress + to add new one",
    invalidInput: "Invalid Input",
    rating: "Rating",
    review: "Review",
    submit: "Submit",
    feedback: "Enter your feedback",
    experience: "How did you find the experience?",
    paymentsuccess: "Payment Success",
    paymentFailed: "Payment Failed. please pay in Cash",
    accept: "Accept",
    seconds: "SEC",
    reject: "Reject"
  },
  fr: {
    Login: "s'identifier",
    signup: "s'inscrire",
    changelanguage: "Changer de langue",
    signin: "Se connecter",
    emailaddress: "Adresse e-mail",
    password: "Mot de passe",
    or: "OU",
    facebook: "Facebook",
    google: "Google+",
    name: "prénom",
    phoneno: "Numéro de téléphone",
    usechar: "Utiliser au moins 8 caractères",
    language: "La Langue",
    myservices: "Mes Services",
    typeOfServices: "Types de services",
    SelectCategory: "Choisir une catégorie",
    SubCategory: "Sous catégorie",
    BecomeTasker: "Devenir un tasker pour voir vos services",
    SelectSubCategories: "Sélectionnez des sous catégories",
    AverageHourlyCost: "Coût horaire moyen",
    Enterfee: "Entrez les frais",
    Address: "Adresse",
    Update: "Mettre à jour",
    Search: "Chercher",
    payment: "Informations de Paiement",
    changepassword: "Changer le mot de passe",
    signout: "Déconnexion",
    taskman: "Bienvenue dans TaskMan",
    organized: "Obtenez votre tâche plus organisée",
    more: "et en faire plus!",
    getorganized: "S'organiser",
    group: "Obtenez des Taskers efficaces",
    submit: "Soumettre",
    oldpassword: "ancien mot de passe",
    newpassword: "nouveau mot de passe",
    repassword: "Re-taper le nouveau mot de passe",
    show: "montrer",
    Explore: "Explorer",
    Home: "Accueil",
    Earnings: "Gains",
    TotalEarnings: "Total des gains",
    TODAY: "AUJOURD'HUI",
    YESTERDAY: "HIER",
    Week: "La semaine",
    Month: "Mois",
    Year: "An",
    Received: "Reçu",
    ReceivedVia: "Via reçu",
    task: "Tâche",
    History: "Histoire",
    bookingHistory: "Historique de réservation",
    Upcoming: "Prochain",
    Past: "Passé",
    NoUpcomingTasks: "Pas de tâches à venir",
    NoTaskHistory: "Aucun historique des tâches",
    ChooseLanguage: "Choisissez la langue",
    EditMyServices: "Modifier mes services",
    BecomeaTasker: "Devenir un Tasker",
    favourite: "Préféré",
    NoFavourite: "Oops! Pas de favori Taskers",
    fetchTaskers: "Récupérer des tâches",
    booking: "Réservation",
    account: "Compte",
    tasker: "Sacs",
    User: "Utilisateur",
    Repair: "Réparation",
    Cleaning: "Nettoyage",
    Health: "Santé",
    Wedding: "Mariage",
    Business: "Entreprise",
    AirConditioning: "Climatisation",
    TV: "la télé",
    Mobile: "Mobile",
    Geyser: "Geyser",
    WashingMachine: "Machine à laver",
    PestControl: "Antiparasitaire",
    Sofa: "Canapé",
    Kitchen: "Cuisine",
    Bathroom: "Salle de bains",
    GymTrainer: "GymTrainer",
    Dietician: "Diététicien",
    Yoga: "Yoga",
    Psychiatrist: "Psychiatre",
    Photographer: "Photographe",
    DJ: "DJ",
    Caterer: "Traiteur",
    MakeupArtist: "Maquilleur",
    Lawyer: "Avocat",
    VisaAgency: "Agence de Visa",
    Developers: "Développeurs",
    CA: "Comptable agréé",
    Designers: "Les concepteurs",
    Primary: "Primaire",
    HighSchool: "École secondaire",
    Engineering: "Ingénierie",
    Medical: "Médical",
    Accountancy: "Comptabilité",
    Tutors: "tuteurs",
    book: "Réserver",
    booknow: "RESERVE MAINTENANT",
    confirmbook: "CONFIRMER LA RÉSERVATION",
    Cancel: "Annuler",
    StartTask: "Démarrer la tâche",
    Start: "Début",
    Done: "Terminé",
    CompleteTask: "Tâche complète",
    CancelBooking: "Annuler la réservation",
    taskInProgress: "Tâche en cours",
    editservice: "Modifier mon service",
    bookingconfirmed: "Réservation confirmée",
    bookingCancelled: "La réservation a été annulée",
    taskerreach: "Tasker atteindra dans quelques minutes",
    taskprogress:
      "Votre tâche demandée est en cours, attendez que la tâche soit terminée",
    payment: "Paiement",
    date: "Rendez-vous amoureux",
    time: "Temps",
    services: "Prestations de service",
    total: "Total",
    userPaying: "Attendre que l'utilisateur paie",
    CollectCash: "Collecter de l'argent",
    price: "prix",
    paymentmethod: "Mode de paiement",
    pay: "Rendez-vous amoureux",
    howtopay: "Sélectionnez comment vous voulez payer",
    card: "Carte de crédit / débit",
    cash: "En espèces",
    choosecard: "Choisissez la carte",
    addCard: "Ajouter une carte",
    selectCard: "Sélectionnez la carte",
    noCards:
      "Vous n'avez aucune carte de crédit enregistrée, \npress + pour en ajouter une nouvelle",
    invalidInput: "entrée invalide",
    rating: "Évaluation",
    review: "La revue",
    submit: "Soumettre",
    feedback: "Entrez vos commentaires",
    experience: "Comment avez-vous trouvé l'expérience?",
    paymentsuccess: "Succès du paiement",
    paymentFailed: "Paiement échoué",
    rateReview: "Rating & Review",
    payCash: "Please Pay Cash",
    seconds: "secondes",
    accept: "Acceptez",
    reject: "Rejeter"
  },
  de: {
    Login: "Anmeldung",
    signup: "Anmelden",
    changelanguage: "Sprache ändern",
    signin: "Sign In",
    emailaddress: "E-Mail-Addresse",
    password: "Passwort",
    or: "Oder",
    facebook: "Facebook",
    google: "Google+",
    name: "Name",
    phoneno: "Telefonnummer",
    usechar: "Verwenden Sie mindestens 8 Zeichen",
    language: "Sprache",
    myservices: "Meine Dienstleistungen",
    typeOfServices: "Arten von Dienstleistungen",
    SelectCategory: "Kategorie wählen",
    SubCategory: "Unterkategorie",
    BecomeTasker: "Werden Sie ein Pfleger, um Ihre Dienste zu sehen",
    SelectSubCategories: "Wählen Sie Unterkategorien",
    AverageHourlyCost: "Durchschnittliche Stundenkosten",
    Enterfee: "Gebühr eingeben",
    Address: "Adresse",
    Update: "Aktualisieren",
    Search: "Suche",
    payment: "Zahlungsinformationen",
    changepassword: "Passwort ändern",
    signout: "Ausloggen",
    taskman: "Willkommen bei TaskMan",
    organized: "Mach deine Aufgabe besser organisiert",
    more: "und mehr erledigen!",
    getorganized: "Organisiert werden",
    group: "Erhalten Sie effiziente Tasker",
    submit: "Einreichen",
    oldpassword: "Altes Passwort",
    newpassword: "Neues Kennwort",
    repassword: "Geben Sie das neue Passwort ein",
    show: "show",
    Explore: "Explorer",
    Home: "Zuhause",
    Earnings: "Verdienste",
    TotalEarnings: "Gesamteinnahmen",
    TODAY: "HEUTE",
    YESTERDAY: "GESTERN",
    Week: "Woche",
    Month: "Monat",
    Year: "Jahr",
    Received: "Empfangen",
    ReceivedVia: "Via erhalten",
    task: "Aufgabe",
    History: "Geschichte",
    bookingHistory: "Buchungsverlauf",
    Upcoming: "Bevorstehende",
    Past: "Vergangenheit",
    NoUpcomingTasks: "Keine bevorstehenden Aufgaben",
    NoTaskHistory: "Kein Aufgabenverlauf",
    ChooseLanguage: "Sprache wählen",
    EditMyServices: "Bearbeiten Sie meine Dienste",
    BecomeaTasker: "Werde ein Tasker",
    favourite: "Favorit",
    NoFavourite: "Hoppla! Kein Favorit Tasker",
    fetchTaskers: "Abrufen von Taskern",
    booking: "Buchung",
    account: "Konto",
    tasker: "Taschen",
    User: "Benutzer",
    Repair: "Reparatur",
    Cleaning: "Reinigung",
    Health: "Gesundheit",
    Wedding: "Hochzeit",
    Business: "Geschäft",
    AirConditioning: "Klimaanlage",
    TV: "Fernseher",
    Mobile: "Mobiltelefon",
    Geyser: "Geysir",
    WashingMachine: "Waschmaschine",
    PestControl: "Schädlingsbekämpfung",
    Sofa: "Sofa",
    Kitchen: "Küche",
    Bathroom: "Bad",
    GymTrainer: "GymTrainer",
    Dietician: "Ernährungsberater",
    Yoga: "Yoga",
    Psychiatrist: "Psychiater",
    Photographer: "Fotograf",
    DJ: "DJ",
    Caterer: "Caterer",
    MakeupArtist: "Visagist",
    Lawyer: "Anwalt",
    VisaAgency: "Visumsagentur",
    Developers: "Entwickler",
    CA: "Wirtschaftsprüfer",
    Designers: "Designer",
    Primary: "Primär",
    HighSchool: "Weiterführende Schule",
    Engineering: "Ingenieurwesen",
    Medical: "Medizinisch",
    Accountancy: "Buchhaltung",
    Tutors: "Tutoren",
    book: "Buchen",
    booknow: "BUCHEN SIE JETZT",
    confirmbook: "BUCHUNG BESTÄTIGEN",
    Cancel: "Stornieren",
    StartTask: "Aufgabe starten",
    Start: "Anfang",
    Done: "Erledigt",
    CompleteTask: "Aufgabe abschließen",
    CancelBooking: "Buchung stornieren",
    taskInProgress: "Aufgabe in Bearbeitung",
    editservice: "Bearbeite meinen Service",
    bookingconfirmed: "Buchung bestätigt",
    bookingCancelled: "Die Buchung wurde storniert",
    taskerreach: "Tasker wird in ein paar Minuten erreichen",
    taskprogress:
      "Die angeforderte Aufgabe wird ausgeführt. Warten Sie, bis die Aufgabe abgeschlossen ist",
    payment: "Zahlung",
    date: "Datum",
    time: "Zeit",
    services: "Dienstleistungen",
    total: "Gesamt",
    userPaying: "Warten Benutzer zahlt",
    CollectCash: "Sammle Geld",
    price: "Preis",
    paymentmethod: "Bezahlverfahren",
    pay: "Zahlen",
    howtopay: "Wählen Sie, wie Sie bezahlen möchten",
    card: "Kredit- / Debitkarte",
    cash: "Kasse",
    choosecard: "Wählen Sie Karte",
    addCard: "Karte hinzufügen",
    selectCard: "Wählen Sie Karte",
    noCards:
      "Sie haben keine gespeicherten Kreditkarten, \n drücken Sie +, um eine neue hinzuzufügen",
    invalidInput: "Ungültige Eingabe",
    rating: "Bewertung",
    review: "Rezension",
    submit: "Einreichen",
    feedback: "Geben Sie Ihr Feedback ein",
    experience: "Wie hast du die Erfahrung gefunden?",
    paymentsuccess: "Zahlungserfolg",
    paymentFailed: "Bezahlung fehlgeschlagen",
    seconds: "Sekunden",
    accept: "Akzeptieren",
    reject: "Ablehnen"
  },
  es: {
    Login: "Iniciar Sesión",
    signup: "Regístrate",
    changelanguage: "Cambiar idioma",
    signin: "Assinar em",
    emailaddress: "Dirección de correo electrónico",
    password: "Contraseña",
    or: "OR",
    facebook: "Facebook",
    google: "Google+",
    name: "Nombre",
    phoneno: "Número De Teléfono",
    usechar: "Usar un mínimo de 8 caracteres",
    language: "Idioma",
    myservices: "Mis Servicios",
    typeOfServices: "Arten von Dienstleistungen",
    SelectCategory: "Kategorie wählen",
    SubCategory: "Subcategoría",
    BecomeTasker: "Conviértase en un tasker para ver sus servicios",
    SelectSubCategories: "Wählen Sie Unterkategorien",
    AverageHourlyCost: "Durchschnittliche Stundenkosten",
    Enterfee: "Gebühr eingeben",
    Address: "Adresse",
    Update: "Aktualisieren",
    Search: "Suche",
    payment: "Información Del Pago",
    changepassword: "Cambia la Contraseña",
    signout: "Desconectar",
    taskman: "Bienvenido a TaskMan",
    organized: "Haz tu tarea más organizada",
    more: "y haz más cosas!",
    getorganized: "Organizarse",
    group: "Obtenga Taskers Eficientes",
    submit: "Enviar",
    oldpassword: "Contraseña Anterior",
    newpassword: "Nueva Contraseña",
    repassword: "Reescriba nueva contraseña",
    show: "espectáculo",
    Explore: "Explorar",
    Home: "Casa",
    Earnings: "Ganancias",
    TotalEarnings: "Ganancias Totales",
    TODAY: "HOY",
    YESTERDAY: "AYER",
    Week: "Semana",
    Month: "Mes",
    Year: "Año",
    Received: "Recibido",
    ReceivedVia: "Recibido a través de",
    task: "Tarea",
    History: "Historia",
    bookingHistory: "Historial de reservas",
    Upcoming: "Próximo",
    Past: "Pasado",
    NoUpcomingTasks: "No hay próximas tareas",
    NoTaskHistory: "Sin historial de tareas",
    ChooseLanguage: "Elige lengua",
    EditMyServices: "Editar mis servicios",
    BecomeaTasker: "Conviértete en Tasker",
    favourite: "Favorito",
    NoFavourite: "Oops!No favorito Taskers",
    fetchTaskers: "Obteniendo Taskers",
    booking: "Reserva",
    account: "Cuenta",
    tasker: "Bolsas",
    User: "Usuario",
    Repair: "Reparar",
    Cleaning: "Limpieza",
    Health: "Salud",
    Wedding: "Boda",
    Business: "Negocio",
    AirConditioning: "Aire acondicionado",
    TV: "televisión",
    Mobile: "Móvil",
    Geyser: "Géiser",
    WashingMachine: "Lavadora",
    PestControl: "Control de plagas",
    Sofa: "Sofá",
    Kitchen: "Cocina",
    Bathroom: "Baño",
    GymTrainer: "Entrenador de gimnasia",
    Dietician: "Dietético",
    Yoga: "Yoga",
    Psychiatrist: "Psiquiatra",
    Photographer: "Fotógrafo",
    DJ: "DJ",
    Caterer: "Abastecedor",
    MakeupArtist: "Maquilladora",
    Lawyer: "Abogado",
    VisaAgency: "Agencia de Visas",
    Developers: "Desarrolladores",
    CA: "Contador Público",
    Designers: "Diseñadores",
    Primary: "Primario",
    HighSchool: "Escuela secundaria",
    Engineering: "Ingenieria",
    Medical: "Médico",
    Accountancy: "Contabilidad",
    Tutors: "tutores",
    book: "Reservar",
    booknow: "RESERVAR AHORA",
    confirmbook: "RESERVA CONFIRMADA",
    Cancel: "Cancelar",
    StartTask: "Iniciar tarea",
    Start: "comienzo",
    Done: "Hecho",
    CompleteTask: "Tarea completa",
    CancelBooking: "Cancelar reserva",
    taskInProgress: "Tarea en progreso",
    editservice: "Editar mi servicio",
    bookingconfirmed: "Reserva confirmada",
    bookingCancelled: "La reserva ha sido cancelada",
    taskerreach: "Tasker llegará en unos minutos",
    taskprogress:
      "Su tarea solicitada está en progreso, espere hasta que se complete la tarea",
    payment: "Pago",
    date: "Fecha",
    time: "Hora",
    services: "Servicios",
    total: "Total",
    userPaying: "El usuario de espera está pagando",
    CollectCash: "Recoge efectivo",
    price: "precio",
    paymentmethod: "Método de pago",
    pay: "Paga",
    howtopay: "Seleccione cómo le gustaría pagar",
    card: "Tarjeta de crédito / débito",
    cash: "Efectivo",
    choosecard: "Elige la tarjeta",
    addCard: "Agregar tarjeta",
    selectCard: "Seleccione la tarjeta",
    noCards:
      "No tiene ninguna tarjeta de crédito guardada, \n presiona + para agregar una nueva",
    invalidInput: "entrada inválida",
    rating: "Clasificación",
    review: "Revisión",
    submit: "Enviar",
    feedback: "Ingrese sus comentarios",
    experience: "¿Cómo encontraste la experiencia?",
    paymentsuccess: "Pago Exitoso",
    paymentFailed: "Pago fallido",
    seconds: "segundos",
    accept: "Aceptar",
    reject: "Rechazar"
  },
  po: {
    Login: "Entrar",
    signup: "Inscrever-se",
    changelanguage: "Mudar idioma",
    signin: "Assinar Em",
    emailaddress: "endereço de e-mail",
    password: "Password",
    or: "OR",
    facebook: "Facebook",
    google: "Google+",
    name: "Name",
    phoneno: "Número de Telefone",
    usechar: "Use no mínimo 8 caracteres",
    language: "Língua",
    myservices: "Meus Serviços",
    typeOfServices: "Tipos de Serviços",
    SelectCategory: "Selecione a Categoria",
    SubCategory: "Subcategoria",
    BecomeTasker: "Torne-se um tasker para ver seus serviços",
    SelectSubCategories: "Selecione Sub Categorias",
    AverageHourlyCost: "Custo médio por hora",
    Enterfee: "Insira a taxa",
    Address: "Endereço",
    Update: "Atualizar",
    Search: "Pesquisa",
    payment: "Informação De Pagamento",
    changepassword: "Mudar Senha",
    signout: "Sair",
    taskman: "Bem vindo ao TaskMan",
    organized: "Torne sua tarefa mais organizada",
    more: "and get more done!",
    getorganized: "Organize-se",
    group: "Obtenha Taskers Eficientes",
    submit: "Enviar",
    oldpassword: "Senha Antiga",
    newpassword: "Nova Senha",
    repassword: "Redigite a nova senha",
    show: "exposição",
    Explore: "Explorar",
    Home: "Casa",
    Earnings: "Ganhos",
    TotalEarnings: "Ganhos totais",
    TODAY: "HOJE",
    YESTERDAY: "ONTEM",
    Week: "Semana",
    Month: "Mês",
    Year: "Ano",
    Received: "Recebido",
    ReceivedVia: "Recebido Via",
    task: "Tarefa",
    History: "História",
    bookingHistory: "Histórico de Reservas",
    Upcoming: "próximos",
    Past: "Passado",
    NoUpcomingTasks: "Não há tarefas futuras",
    NoTaskHistory: "Nenhum histórico de tarefas",
    ChooseLanguage: "Escolha o seu idioma",
    EditMyServices: "Editar meus serviços",
    BecomeaTasker: "Torne-se um Tasker",
    favourite: "Favorito",
    NoFavourite: "Opa! Nenhum favorito Taskers",
    fetchTaskers: "Buscando Taskers",
    booking: "Reserva",
    account: "Conta",
    tasker: "Sacos",
    User: "Do utilizador",
    Repair: "Reparar",
    Cleaning: "Limpeza",
    Health: "Saúde",
    Wedding: "Casamento",
    Business: "O negócio",
    AirConditioning: "Ar condicionado",
    TV: "televisão",
    Mobile: "Móvel",
    Geyser: "Gêiser",
    WashingMachine: "Máquina de lavar",
    PestControl: "Controle de pragas",
    Sofa: "Sofá",
    Kitchen: "Cozinha",
    Bathroom: "Banheiro",
    GymTrainer: "Treinador de Ginásio",
    Dietician: "Nutricionista",
    Yoga: "Ioga",
    Psychiatrist: "Psiquiatra",
    Photographer: "Fotógrafo",
    DJ: "DJ",
    Caterer: "Fornecedor",
    MakeupArtist: "Maquiador",
    Lawyer: "Advogado",
    VisaAgency: "Agência Visa",
    Developers: "Desenvolvedores",
    CA: "Revisor oficial de contas",
    Designers: "Designers",
    Primary: "Primário",
    HighSchool: "Colegial",
    Engineering: "Engenharia",
    Medical: "Médico",
    Accountancy: "Contabilidade",
    Tutors: "tutores",
    book: "Reservar",
    booknow: "LIVRO AGORA",
    confirmbook: "CONFIRMAR RESERVAS",
    Cancel: "Cancelar",
    StartTask: "Iniciar tarefa",
    Start: "Começar",
    Done: "Feito",
    CompleteTask: "Tarefa Completa",
    CancelBooking: "Cancelar a reserva",
    taskInProgress: "Tarefa em andamento",
    editservice: "Editar meu serviço",
    bookingconfirmed: "Reserva confirmada",
    bookingCancelled: "A reserva foi cancelada",
    taskerreach: "Tasker alcançará em poucos minutos",
    taskprogress:
      "Sua tarefa solicitada está em andamento, espere até que a tarefa seja concluída",
    payment: "Pagamento",
    date: "Datar",
    time: "Tempo",
    services: "Serviços",
    total: "Total",
    userPaying: "Aguarde o usuário está pagando",
    CollectCash: "Colete Dinheiro",
    price: "preço",
    paymentmethod: "Método de pagamento",
    pay: "Pagamento",
    howtopay: "Selecione como você gostaria de pagar",
    card: "Cartão de Crédito / Débito",
    cash: "Dinheiro",
    choosecard: "Escolha o cartão",
    addCard: "Adicionar cartão",
    selectCard: "Selecione o cartão",
    noCards:
      "Você não possui cartões de crédito salvos, \n pressione + para adicionar um novo",
    invalidInput: "entrada inválida",
    rating: "Avaliação",
    review: "Reveja",
    submit: "Enviar",
    feedback: "Digite seu feedback",
    experience: "Como você encontrou a experiência?",
    paymentsuccess: "Pagamento em Sucesso",
    paymentFailed: "Pagamento falhou",
    seconds: "segundos",
    accept: "Aceitar",
    reject: "Rejeitar"
  },
  jp: {
    Login: "ログイン",
    signup: "サインアップ",
    changelanguage: "言語を変えてください",
    signin: "サインイン",
    emailaddress: "電子メールアドレス",
    password: "パスワード",
    or: "または",
    facebook: "フェイスブック",
    google: "Google+",
    name: "名",
    phoneno: "電話番号",
    usechar: "少なくとも8文字を使用してください",
    language: "言語",
    myservices: "私のサービス",
    typeOfServices: "サービスの種類",
    SelectCategory: "カテゴリを選んでください",
    SubCategory: "サブカテゴリ",
    BecomeTasker: "あなたのサービスを見るために仕事になる",
    SelectSubCategories: "サブカテゴリを選択",
    AverageHourlyCost: "平均時間コスト",
    Enterfee: "手数料を入力",
    Address: "住所",
    Update: "更新",
    Search: "サーチ",
    payment: "支払情報",
    changepassword: "パスワードを変更する",
    signout: "サインアウト",
    taskman: "TaskManへようこそ",
    organized: "より組織化されたタスクを得る",
    more: "もっと完了してください！",
    getorganized: "組織する",
    group: "効率的な指導者を得る",
    submit: "提出する",
    oldpassword: "以前のパスワード",
    newpassword: "新しいパスワード",
    repassword: "新しいパスワード再入力",
    show: "ショー",
    Explore: "探検する",
    Home: "ホーム",
    Earnings: "収益",
    TotalEarnings: "総収入",
    TODAY: "今日",
    YESTERDAY: "昨日",
    Week: "週間",
    Month: "月",
    Year: "年",
    Received: "受け取った",
    ReceivedVia: "受信ビア",
    task: "仕事",
    History: "歴史",
    bookingHistory: "予約履歴",
    Upcoming: "今後の予定",
    Past: "過去",
    NoUpcomingTasks: "今後の予定はありません",
    NoTaskHistory: "タスク履歴なし",
    ChooseLanguage: "言語を選択",
    EditMyServices: "マイサービスを編集する",
    BecomeaTasker: "タスク担当者になる",
    favourite: "お気に入り",
    NoFavourite: "おっとっと！いいえお気に入り タスク担当者",
    fetchTaskers: "タスク担当者の取得",
    booking: "予約",
    account: "アカウント",
    tasker: "バッグ",
    User: "ユーザー",
    Repair: "修復",
    Cleaning: "クリーニング",
    Health: "健康",
    Wedding: "結婚式",
    Business: "ビジネス",
    AirConditioning: "空調",
    TV: "テレビ",
    Mobile: "モバイル",
    Geyser: "間欠泉",
    WashingMachine: "洗濯機",
    PestControl: "害虫防除",
    Sofa: "ソファー",
    Kitchen: "キッチン",
    Bathroom: "バスルーム",
    GymTrainer: "ジムトレーナー",
    Dietician: "栄養士",
    Yoga: "ヨガ",
    Psychiatrist: "精神科医",
    Photographer: "写真家",
    DJ: "ディスクジョッキー",
    Caterer: "料理人",
    MakeupArtist: "メイクアップアーティスト",
    Lawyer: "弁護士",
    VisaAgency: "ビザ代理店",
    Developers: "開発者",
    CA: "公認会計士",
    Designers: "デザイナー",
    Primary: "一次",
    HighSchool: "高校",
    Engineering: "エンジニアリング",
    Medical: "医療",
    Accountancy: "会計学",
    Tutors: "教師",
    book: "申し込む",
    booknow: "今予約する",
    confirmbook: "予約確認",
    Cancel: "キャンセル",
    StartTask: "タスクを開始する",
    Start: "開始",
    Done: "完了",
    CompleteTask: "完全なタスク",
    CancelBooking: "キャンセル予約",
    taskInProgress: "進行中のタスク",
    editservice: "私のサービスを編集する",
    bookingconfirmed: "予約確定",
    bookingCancelled: "予約はキャンセルされました",
    taskerreach: "タスク担当者は数分でアクセスします",
    taskprogress:
      "あなたの要求されたタスクは進行中です。タスクが完了するまで待ってください。",
    payment: "支払い",
    date: "年月日",
    time: "時間",
    services: "サービス",
    total: "全額",
    userPaying: "ユーザーが支払いを待っている",
    CollectCash: "現金を集める",
    price: "価格",
    paymentmethod: "支払方法",
    pay: "支払う",
    howtopay: "お支払い方法の選択",
    card: "クレジット/デビットカード",
    cash: "金銭",
    choosecard: "カードを選ぶ",
    addCard: "カードを追加",
    selectCard: "カードの選択",
    noCards:
      "保存したクレジットカードはありません。\nを押して新しいカードを追加してください",
    invalidInput: "無効入力",
    rating: "格付け",
    review: "見直し",
    submit: "提出する",
    feedback: "あなたのフィードバックを入力してください",
    experience: "どのように経験を見つけましたか？",
    paymentsuccess: "支払いの成功",
    paymentFailed: "支払いに失敗しました",
    seconds: "秒",
    accept: "受け入れる",
    reject: "拒む"
  },
  ch: {
    Login: "登录",
    signup: "注册",
    changelanguage: "改变语言",
    signin: "签到",
    emailaddress: "电子邮件地址",
    password: "密码",
    or: "要么",
    facebook: "Facebook",
    google: "Google+",
    name: "名称",
    phoneno: "电话号码",
    usechar: "至少使用8个字符",
    language: "语言",
    myservices: "我的服务",
    typeOfServices: "服务类型",
    SelectCategory: "选择类别",
    SubCategory: "子类别",
    BecomeTasker: "成为一名任务员，以查看您的服务",
    SelectSubCategories: "选择子类别",
    AverageHourlyCost: "平均每小时成本",
    Enterfee: "输入费用",
    Address: "地址",
    Update: "更新",
    Search: "搜索",
    payment: "支付信息",
    changepassword: "更改密码",
    signout: "登出",
    taskman: "欢迎来到TaskFun",
    organized: "让您的任务更有条理",
    more: "并做得更多！",
    getorganized: "组织起来",
    group: "获得高效的服务员",
    submit: "提交",
    oldpassword: "舊密碼",
    newpassword: "新密碼",
    repassword: "重新輸入新密碼",
    show: "顯示",
    Explore: "探索",
    Home: "家",
    Earnings: "收益",
    TotalEarnings: "总收入",
    TODAY: "今天",
    YESTERDAY: "昨天",
    Week: "周",
    Month: "月",
    Year: "年",
    Received: "收到",
    ReceivedVia: "收到 通过",
    task: "任务",
    History: "历史",
    bookingHistory: "预订历史",
    Upcoming: "即将到来",
    Past: "过去",
    NoUpcomingTasks: "没有即将到来的任务",
    NoTaskHistory: "没有任务历史",
    ChooseLanguage: "选择语言",
    EditMyServices: "编辑我的服务",
    BecomeaTasker: "成为一个 手袋",
    favourite: "喜爱",
    NoFavourite: "哎呀！不喜欢 一心",
    fetchTaskers: "取 一心",
    booking: "预订",
    account: "帐户",
    tasker: "手袋",
    User: "用户",
    Repair: "修理",
    Cleaning: "清洁的",
    Health: "健康",
    Wedding: "婚礼",
    Business: "商业",
    AirConditioning: "空调",
    TV: "电视",
    Mobile: "移动",
    Geyser: "喷泉",
    WashingMachine: "洗衣机",
    PestControl: "除害虫",
    Sofa: "沙发",
    Kitchen: "厨房",
    Bathroom: "浴室",
    GymTrainer: "健身教练",
    Dietician: "营养师",
    Yoga: "瑜伽",
    Psychiatrist: "心理医生",
    Photographer: "摄影师",
    DJ: "唱片骑师",
    Caterer: "熟食店",
    MakeupArtist: "彩妆大师",
    Lawyer: "律师",
    VisaAgency: "签证机构",
    Developers: "开发商",
    CA: "特许会计师",
    Designers: "设计师",
    Primary: "主",
    HighSchool: "中学",
    Engineering: "工程",
    Medical: "医",
    Accountancy: "会计",
    Tutors: "导师",
    book: "定",
    booknow: "现在预订",
    confirmbook: "确认预订",
    Cancel: "取消",
    StartTask: "开始任务",
    Start: "开始",
    Done: "完成",
    CompleteTask: "完成任务",
    CancelBooking: "取消预订",
    taskInProgress: "任务正在进行中",
    editservice: "编辑我的服务",
    bookingconfirmed: "预订确认",
    bookingCancelled: "预订已被取消",
    taskerreach: "Tasker将在几分钟内到达",
    taskprogress: "您请求的任务正在进行中，等待任务完成",
    payment: "付款",
    date: "日期",
    time: "时间",
    services: "服务",
    total: "总",
    userPaying: "等待用户付款",
    CollectCash: "收集现金",
    price: "価格",
    paymentmethod: "付款方法",
    pay: "付款",
    howtopay: "选择您想要的付款方式",
    card: "信用卡/借记卡",
    cash: "现金",
    choosecard: "选择卡片",
    addCard: "添加卡片",
    selectCard: "选择卡",
    noCards: "您没有任何已保存的信用卡，\n按+添加新信用卡",
    invalidInput: "输入无效",
    rating: "评分",
    review: "回顾",
    submit: "呈递",
    feedback: "输入您的反馈",
    experience: "你是怎么找到这种体验的？",
    paymentsuccess: "付款成功",
    paymentFailed: "支払いに失敗しました",
    seconds: "秒",
    accept: "接受",
    reject: "拒绝"
  }
};

export default lang;
